install! 'cocoapods',
disable_input_output_paths: true,
generate_multiple_pod_projects: true


source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
targetsArray = ['JuTuanLife', 'JuTuanLife_ent']
# 循环
targetsArray.each do |t|
  target t do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JuTuanLife

#  pod 'WCBaseUIKit'
pod 'WCModule'
pod 'WCModule/RegexKitLite'
#pod 'WCModel'
#pod 'WCNetKit'
pod 'WCPlugin'

#微信分享
#pod 'WechatOpenSDK'
pod 'WechatOpenSDK_NoPay'

#友盟统计、日志
pod 'UMCAnalytics'
pod 'UMCCommonLog'

  end
end
